# Generated by Django 3.2.12 on 2022-02-17 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyurtma',
            name='mahsulot',
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='savat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asosiy.savat'),
        ),
    ]
