# Generated by Django 3.2.12 on 2022-02-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0004_alter_mahsulot_aksiya'),
        ('asosiy', '0002_auto_20220217_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyurtma',
            name='status',
            field=models.CharField(default='Jarayonda', max_length=50),
        ),
        migrations.RemoveField(
            model_name='tanlangan',
            name='mahsulot',
        ),
        migrations.AddField(
            model_name='tanlangan',
            name='mahsulot',
            field=models.ManyToManyField(to='buyurtma.Mahsulot'),
        ),
    ]
