# Generated by Django 3.2.12 on 2022-02-11 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('rasm', models.FileField(upload_to='bolim_rasmi')),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('batafsil', models.CharField(max_length=350)),
                ('rasm', models.FileField(upload_to='mahsulot_rasmi')),
                ('brend', models.CharField(max_length=50)),
                ('mamlakat', models.CharField(max_length=50)),
                ('vazn', models.CharField(max_length=50)),
                ('narx', models.IntegerField()),
                ('mavjud', models.BooleanField(default=True)),
                ('bolim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buyurtma.bolim')),
            ],
        ),
        migrations.CreateModel(
            name='Sharh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baho', models.PositiveIntegerField(default=1)),
                ('matn', models.CharField(max_length=400)),
                ('sana', models.DateField(auto_now_add=True)),
                ('mahsulot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buyurtma.mahsulot')),
                ('mijoz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.mijoz')),
            ],
        ),
    ]
