# Generated by Django 3.2.12 on 2022-02-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='aksiya',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
