# Generated by Django 3.2.12 on 2022-02-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0002_mahsulot_aksiya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharh',
            name='baho',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
