# Generated by Django 3.2.12 on 2022-02-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0003_alter_sharh_baho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='aksiya',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
    ]
